### ISSUE TITLE
Bug(transloco-scoped-libs):

### ISSUE THREAD

**Issue by bjornharvold** [ngneat/transloco#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Scoped Libs

### Is this a regression?

Yes

### Current behavior

Since upgrading to v3.0.2 / v3.0.0 of transloco and transloco-scoped-libs respectively, when I execute the transloco-scoped-libs command, I get this error:

```
> iko@13.11.3 transloco:extract-scoped-libs /Users/crash/git/iko-travel-spa
> transloco-scoped-libs

/Users/crash/git/iko-travel-spa/node_modules/@ngneat/transloco-scoped-libs/src/index.js:11
const { watch, ['skip-gitignore']: skipGitIgnoreUpdate } = command_line_args_1.default(optionDefinitions);
                                                                                      ^

TypeError: command_line_args_1.default is not a function
    at Object.<anonymous> (/Users/crash/git/iko-travel-spa/node_modules/@ngneat/transloco-scoped-libs/src/index.js:11:87)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

```

### Expected behavior

It should be copying the resources to its respective destinations as it did in the versions prior to 3.x.

### Please provide a link to a minimal reproduction of the bug

https://github.com/bjornharvold/transloco-issue-515

### Transloco Config

```markdown
{
      provide: TRANSLOCO_CONFIG,
      useValue: {
        availableLangs: [{ id: 'en', label: 'English' }],
        reRenderOnLangChange: false,
        defaultLang: 'en',
        fallbackLang: 'en',
        prodMode: environment.production,
        scopeStrategy: 'shared'
      } as TranslocoConfig
    }
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 3.0.2
Angular: 12.2.9
Node: 14.5
Package Manager: yarn
OS: Mac OS
```

### Browser

```markdown
NA
```

### I would like to make a pull request for this bug

No

**Comment by bjornharvold** [comment]
Yes correct, previous versions work fine. Submitting a regression bug here.

**Comment by burl21** [comment]
I have the same error with transloco-optimize.

`
transloco-optimize dist/Name/assets/i18n

node_modules/@ngneat/transloco-optimize/src/index.js:10
const { dist, commentsKey } = command_line_args_1.default(optionDefinitions);
                                                                                                  ^

TypeError: command_line_args_1.default is not a function
    at Object.<anonymous> (node_modules/@ngneat/transloco-optimize/src/index.js:10:58)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
`

`
    "@ngneat/transloco-optimize": "^3.0.0",
    "@ngneat/transloco": "^3.0.6",
 `
